name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository containing the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using the credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Build the Docker image using the Dockerfile in the repository
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/crowd:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/crowd:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/crowd:6.1.1

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/crowd:6.1.1 --push .
